# Tap 必要的仓库
tap "homebrew/cask"
tap "homebrew/cask-versions"

# 安装命令行工具 (Formulas)
brew "vim"
brew "neovim"
brew "tmux"
brew "alacritty"
brew "stow"
brew "yazi"
brew "docker"
brew "podman"
brew "lazydocker"
brew "btop"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "zoxide"
brew "git-flow"
brew "git-secrets"
brew "lazygit"
brew "node"
brew "yarn"
brew "go"
brew "pipenv"
brew "pyenv"
brew "rbenv"
brew "ruby-build"

# 安装桌面应用 (Casks)
cask "firefox"
cask "google-chrome"
cask "arc"
cask "ghostty"
cask "raycast"
cask "rustdesk"
cask "betterdisplay"
cask "slack"
cask "cursor"
cask "input-source-pro"
cask "apidog"
cask "obsidian"
cask "tailscale"
cask "claude"
cask "orbstack"
cask "zoom"
